name: Build Android App

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build Android App (.apk + .so)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Ensure jniLibs directories exist
        run: |
          mkdir -p app/src/main/jniLibs/arm64-v8a
          mkdir -p app/src/main/jniLibs/armeabi-v7a

      - name: Download latest libtruth_core.so from truth-training (build-android.yml)
        id: download_so
        uses: dawidd6/action-download-artifact@v6
        continue-on-error: true
        with:
          github_token: ${{ secrets.TRUTH_TRAINING_TOKEN || github.token }}
          workflow: build-android.yml
          repo: ekwator/truth-training
          workflow_conclusion: success
          name: truth-android-build
          path: app/src/main/jniLibs
          if_no_artifact_found: warn

      - name: Verify libtruth_core.so exists for both architectures
        run: |
          for ARCH in arm64-v8a armeabi-v7a; do
            SO_FILE=app/src/main/jniLibs/$ARCH/libtruth_core.so
            if [ ! -f "$SO_FILE" ]; then
              echo "libtruth_core.so not found in $ARCH"
              exit 1
            else
              echo "libtruth_core.so is ready for $ARCH: $SO_FILE"
            fi
          done

      - name: Ensure Gradle permissions
        run: chmod +x ./gradlew

      - name: Build Android app (Debug)
        run: ./gradlew --no-daemon assembleDebug

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: truth-android-app
          path: |
            app/build/outputs/apk/debug/app-debug.apk
            app/src/main/jniLibs/arm64-v8a/libtruth_core.so
            app/src/main/jniLibs/armeabi-v7a/libtruth_core.so
          if-no-files-found: error

